hostel_app/urls.py
from django.urls import path
from hostel_app import views

app_name = 'hostel_app'

urlpatterns = [
    path('register/',views.reg, name = "reg"),
    path('user_login/',views.user_login, name='user_login'),
    
    path('warden_register',views.warden_reg , name='warden_reg'),
    path('student_list/',views.StudentList, name='student-list'),
    path('hostel/',views.HostelList, name = 'hostel-list'),
    path('mess_details/',views.mess_details, name='mess-display'),

    path('hostel_details/',views.HostelWiseView, name='hostel-details'),
    path('hostel/student_list/',views.HostelStudentList, name='hostel-student-list'),
    path('profile/',views.StudentProfileView, name='student-details'),
    path('profile/edit',views.edit, name='edit-profile'),
    path('add_vehicle/',views.add_vehicle, name='add-vehicle'),
    path('warden_list/',views.warden_list, name='warden_list'),

    path('warden/add_room',views.add_room, name='warden-add-room'),
    path('warden/add_hostel',views.add_hostel, name='warden-add-hostel'),
    path('warden/add_mess',views.add_mess, name='warden-add-mess'),
    path('veh_list/',views.vehicle_list, name='vehicle_list'),

    path('clg_info/',views.clg_info, name='clg-form')


]

hostel_management/urls.py
from django.contrib import admin
from django.urls import path,include
from hostel_app import views

urlpatterns = [
    path('',views.index, name="index"),
    path('hostel_app/',include('hostel_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout , name='logout'),
]

hostel_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator 

# Create your models here.
class Student(models.Model):

    user = models.OneToOneField(User,max_length=7,on_delete=models.CASCADE)
    student_name = models.CharField(max_length=50)
    own = [('Y',"Yes"),('N',"No")]
    own_vehicle = models.CharField(choices=own, max_length=1, default='N')
    # hostel_b = models.ForeignKey("Hostel",on_delete=models.SET_NULL,null=True)
    room = models.ForeignKey("Room",on_delete=models.SET_NULL,null=True)
    mis_id = models.ForeignKey("CollegeInfo",null=False,on_delete=models.CASCADE,default='0000000')
    gender_choice = [('M',"Male"),('F',"Female")]
    gender = models.CharField(choices=gender_choice, max_length=1, default=None , null=False)
    
    def clean(self):
        if (self.gender and self.room != None):
            if self.gender != self.room.hostel.gender:
                raise ValidationError("Sorry. We don't offer mixed hostels.")
            if self.room.room_alloted==True:
                raise ValidationError('Room is already alotted.')
        # if Student.objects.filter(user__username__iexact=user.username).exists() :
        #     raise ValidationError("User already exists")
        # elif not re.match(r"[mbp]\d{6}[a-z][a-z]",str(user.username),re.I):
        #     print("Invalid Roll No")

    def __str__(self):
        return self.user.id
class vehicle(models.Model):
    vehicleno = models.CharField(max_length=20,primary_key=True)
    licence =  models.BigIntegerField(null=True)#on_delete=models.SET_NULL,null=True)
    h_id = models.ForeignKey("Student", on_delete=models.CASCADE)#, primary_key=True)#on_delete=models.CASCADE)
    
    def __str__(self):
        return vehicleno   


class CollegeInfo(models.Model):
    mis = models.CharField(unique=True, max_length=7, primary_key=True)
    
    email = models.CharField( max_length=50,null=True)#on_delete=models.SET_NULL,null=True)
    phone_no = models.BigIntegerField(null=True)#on_delete=models.SET_NULL,null=True)
    # branch = models.CharField(db_column='BRANCH', max_length=20,null=True)
    batchof = models.PositiveIntegerField(default=2023, validators=[MinValueValidator(2000), MaxValueValidator(2025)])

    # branch = models.ForeignKey("Branch",on_delete=models.SET_NULL,null=True)
    branch = models.CharField(max_length=25,null=True)

    def __str__(self):
        return self.mis

class Hostel(models.Model):

    hostel_name = models.CharField(max_length=25, primary_key=True)
    warden = models.ForeignKey("wardenInfo", on_delete=models.SET_NULL,null=True)
    gender_choice = [('M',"Male"),('F',"Female")]
    gender = models.CharField(choices=gender_choice, max_length=1, default=None)
    mess = models.OneToOneField("Mess", on_delete=models.SET_NULL,null=True)
    # rector = models.CharField(max_length=25)
    # b_phone_no = models.BigIntegerField(null=True)
    # totroom = models.IntegerField(default=0)
    def __str__(self):
        return self.hostel_name

class Mess(models.Model):
    mess_name = models.CharField(max_length=25,default="COEP-Mess")
    mess_type = models.CharField(max_length=50)
    contractor = models.CharField(max_length=50,null=True)
    daily_fees = models.IntegerField(null=True)

    def __str__(self):
        return self.mess_name

class Room(models.Model):

    hostel = models.ForeignKey("Hostel", on_delete=models.CASCADE)
    room_num = models.IntegerField()
    room_alloted = models.BooleanField(default=False)
    # capacity = models.IntegerField(min_value=1,max_value=4,default=1)
    capacity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(0), MaxValueValidator(1)])

    def __str__(self):
        ret_str = str(self.hostel) + "-" + str(self.room_num)
        return ret_str
        # return room_num
    class Meta:
        unique_together = ('hostel','room_num',)
        ordering = ['hostel','room_num']

# class Branch(models.Model):

#     branch_code = models.CharField(max_length=50,primary_key=True)
#     branch_name = models.CharField(max_length=50)
#     faculty = models.CharField(max_length=50)

    # def __str__(self):
    #     return self.branch_name
class wardenInfo(models.Model):
    name = models.CharField(unique=True, max_length=50, primary_key=True)
    email = models.CharField(max_length=50,null=True)#on_delete=models.SET_NULL,null=True)
    phone_no = models.BigIntegerField(null=True)#on_delete=models.SET_NULL,null=True)
    gender_choice = [('M',"Male"),('F',"Female")]
    gender = models.CharField(choices=gender_choice, max_length=1, default=None)
    # hostel = models.ForeignKey("Hostel",on_delete=models.SET_NULL,null=True)
    slot_c = [('M',"Morning"),('N',"Night")]
    slot = models.CharField(choices=slot_c, max_length=1, default=None)
    
    def __str__(self):
        return self.name

hostel_app/views.py
from django.shortcuts import render, redirect
from hostel_app import forms

from django.urls import reverse
from hostel_app.models import Student,Room,Hostel,CollegeInfo,Mess,wardenInfo,vehicle
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import re

# Create your views here.

def index(request):
    return render(request,'hostel_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

# for rex  in Mess.objects.raw('select * from hostel_app_mess'):
#     print(rex)

def reg(request):

    registered = False

    if request.method == 'POST':
        user_form = forms.UserForm(request.POST)
        student_form = forms.StudentForm(request.POST)
        # clg_form = forms.ClgForm(request.POST)

        if user_form.is_valid() and student_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)  #For hashing passwords
            user.save()

            student = student_form.save(commit=False)
            student.user = user;

            #b = Room.objects.get(hostel = student.room.hostel , room_num = student.room.room_num)
            b = Room.objects.raw('SELECT * FROM hostel_app_room WHERE room_num = %s and hostel_id =%s',[student.room.room_num,student.room.hostel])[0]
            b.room_alloted = True;
            b.save()

            # clg = clg_form.save(commit=False)
            # clg.save()
            student.save()
            registered = True

        else:
            print(user_form.errors , student_form.errors )

    else:
        user_form = forms.UserForm()
        student_form = forms.StudentForm()
        # clg_form = forms.ClgForm()

    #boys_hostel = Hostel.objects.filter(gender="M")
    #girls_hostel = Hostel.objects.filter(gender="F")
    validmis = CollegeInfo.objects.raw('SELECT mis FROM hostel_app_collegeinfo');
    
    boys_hostel = Hostel.objects.raw('SELECT * FROM hostel_app_hostel WHERE gender="M"');
    girls_hostel = Hostel.objects.raw('SELECT * FROM hostel_app_hostel WHERE gender="F"');

    return render(request,'hostel_app/reg.html',
                            {'user_form':user_form,
                            'student_form':student_form,
                            'registered':registered,
                            'boys_hostel':boys_hostel,
                            'validmis':validmis,
                            'girls_hostel':girls_hostel})


@login_required
def edit(request):
    current_student = Student.objects.raw('SELECT h.* FROM hostel_app_student as h ,auth_user as a WHERE a.id=h.user_id and a.username=%s',[request.user.get_username()])[0]
    current_hostel = current_student.room.hostel.hostel_name
    current_room = current_student.room.room_num
    if request.method == 'POST':
        #Deallocating current room
        #b = Room.objects.get(hostel = current_hostel , room_num = current_room)
        b = Room.objects.raw('SELECT * FROM hostel_app_room WHERE room_num = %s and hostel_id =%s',[current_room,current_hostel])[0]
        b.room_alloted = False;
        b.save()

        student_form = forms.StudentForm(request.POST, instance=request.user.student)
        if student_form.is_valid():
            current_student = Student.objects.raw('SELECT h.* FROM hostel_app_student as h ,auth_user as a WHERE a.id=h.user_id and a.username=%s',[request.user.get_username()])[0]
            current_hostel = current_student.room.hostel.hostel_name
            current_room = current_student.room.room_num

            student = student_form.save(commit=False)

            #Allocating new room
            #b = Room.objects.get(hostel = student.room.hostel , room_num = student.room.room_num)
            b = Room.objects.raw('SELECT * FROM hostel_app_room WHERE room_num = %s and hostel_id =%s',[student.room.room_num,student.room.hostel])[0]
            b.room_alloted = True;
            b.save()

            student.save()
            return StudentProfileView(request)
        else:
            #Re-allocating current room
            #b = Room.objects.get(hostel = current_hostel , room_num = current_room)
            b = Room.objects.raw('SELECT * FROM hostel_app_room WHERE room_num = %s and hostel_id =%s',[current_room,current_hostel])[0]
            b.room_alloted = True;
            b.save()
    else:
        student_form = forms.StudentForm(instance=request.user.student)

    #boys_hostel = Hostel.objects.filter(gender="M")
    #girls_hostel = Hostel.objects.filter(gender="F")
    boys_hostel = Hostel.objects.raw('SELECT * FROM hostel_app_hostel WHERE gender="M"');
    girls_hostel = Hostel.objects.raw('SELECT * FROM hostel_app_hostel WHERE gender="F"');

    return render(request,'hostel_app/profile_edit.html',
                            {'student_form':student_form,
                            'boys_hostel':boys_hostel,
                            'girls_hostel':girls_hostel})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username , password = password)

        if user is not None:
            if user.is_active:
                login(request,user)
                if username=="chief_warden":
                    return HttpResponseRedirect(reverse('index'))
                else:
                    return StudentProfileView(request)
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details")
    else:
        return render(request,'hostel_app/login.html')

from django.views import generic

def HostelList(request):
    #hostel = Hostel.objects.all()
    hostel = Hostel.objects.raw('SELECT * FROM hostel_app_hostel')
    context = {
        'hostel_list':hostel,
    }
    return render(request,'hostel_app/hostel_list.html',
                            context=context)

@login_required
def HostelWiseView(request):
    #current_student = Student.objects.get(user__username=request.user.get_username())
    current_student = Student.objects.raw('SELECT h.* FROM hostel_app_student as h ,auth_user as a WHERE a.id=h.user_id and a.username=%s',[request.user.get_username()])[0]
    hostel_name = current_student.room.hostel.hostel_name
    #students = Student.objects.filter(room__hostel__hostel_name=hostel_name)
    #count = students.count()
    #hostel = Hostel.objects.get(hostel_name=hostel_name)
    students = Student.objects.raw('SELECT s.* FROM hostel_app_student s, hostel_app_room r WHERE s.room_id=r.id and hostel_id=%s',[hostel_name])
    count = len(students)
    hostel = Hostel.objects.raw('SELECT * FROM hostel_app_hostel WHERE hostel_name=%s',[hostel_name])[0]
    context = {
        'students':students,
        'hostel':hostel,
        'num_students': count,
    }
    return render(request,'hostel_app/hostelwise_details.html',
                            context=context)

def StudentList(request):
    #student = Student.objects.all()
    student = Student.objects.raw('SELECT * FROM hostel_app_student')
    clg = CollegeInfo.objects.raw('SELECT * FROM hostel_app_collegeinfo')
    context = {
        'student_list':student,
        'clg_list':clg
    }
    return render(request,'hostel_app/student_list.html',
                            context=context)

@login_required
def HostelStudentList(request):
    #current_student = Student.objects.get(user__username=request.user.get_username())
    current_student = Student.objects.raw('SELECT h.* FROM hostel_app_student as h ,auth_user as a WHERE a.id=h.user_id and a.username=%s',[request.user.get_username()])[0]
    hostel_name = current_student.room.hostel.hostel_name
    students = Student.objects.filter(room__hostel__hostel_name=hostel_name).order_by('room__room_num')
    row_count = students.count()
    students = Student.objects.raw('SELECT s.* FROM hostel_app_student s, hostel_app_room r WHERE s.room_id=r.id and hostel_id=%s order by r.room_num',[hostel_name])
    n = 4
    students_list = [students[i * n:(i + 1) * n] for i in range((len(students) + n - 1) // n )]
    context = {
        'student_list':students_list,
        'num_rows':range(row_count),
    }
    return render(request,'hostel_app/hostel_student_list.html',
                            context=context)

@login_required
def StudentProfileView(request):

    #student = Student.objects.get(user__username = current_user)
    current_user = request.user.get_username()
    student = Student.objects.raw('SELECT h.* FROM hostel_app_student as h ,auth_user as a WHERE a.id=h.user_id and a.username=%s',[current_user])[0]
    clg = CollegeInfo.objects.raw('SELECT * FROM hostel_app_collegeinfo where mis=%s',[student.mis_id_id])[0]
    # # for e in clg:
    # print(clg.batchof)
    context = {
        'student':student,
        'clg':clg
    }
    return render(request,'hostel_app/student_details.html',
                            context=context)

@login_required
def add_room(request):

    print(request.user.get_username())
    current_user = request.user.get_username()
    warden = True
    if current_user!="chief_warden":
        warden = False

    room_added = False
    if request.method == 'POST':
        room_form = forms.RoomForm(request.POST)
        if room_form.is_valid():
            room = room_form.save(commit=False)
            room.save()
            room_added = True;
    else:
        room_form = forms.RoomForm()

    return render(request,'hostel_app/add_room.html',
                                {'room_form':room_form, 'room_added':room_added, 'is_warden':warden})

@login_required
def add_hostel(request):

templates/hostel_app/add_hostel.html
<!DOCTYPE html>
{% extends "hostel_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
<div>
  {% if not is_warden %}
    <h2 style="text-align:center;">Only warden can add new Hostel</h2>
  {% else %}
    <!-- <h1>Add Hostel</h1> -->
    <div class="main-w3layouts wrapper">
      <div class="main-agileinfo">
        <div class="agileits-top">
          {% if hostel_added %}
            <script>
            alert("Hostel Added!!");
            </script>
          {% endif %}
          <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% if hostel_form.errors %}
              <div class="alert alert-danger" role="alert">
                <div class="error">
                   <ul>
                     {% for key,value in hostel_form.errors.items %}
                      {% for error in value %}
                        <li>{{ error }}</li>
                      {% endfor %}
                     {% endfor %}
                   </ul>
                </div>
              </div>
            {% endif %}
            <!-- HostelForm -->

            <div class="form-group">
              <label for="id_hostel_name"> Hostel Name </label>
              <input required class="textarea-css" type="text" name="hostel_name" placeholder="Hostel Name" value="{% if hostel_form.hostel_name.value %}{{hostel_form.hostel_name.value}}{% else %}{% endif %}">
            </div>
<!-- 
            <div class="form-group">
              <label for="id_warden"> Warden </label>
              <input required class="textarea-css" type="text" name="warden" placeholder="Warden" value="{% if hostel_form.warden.value %}{{hostel_form.warden.value}}{% else %}{% endif %}">
            </div> -->
            <div class="form-group">
              <label for="id_warden"> Warden </label>
              <select required id="id_warden" name="warden" placeholder="Warden" class="select-css">
                {% for value,key in hostel_form.fields.warden.choices %}
                    <option value="{{ value }}"{% if hostel_form.warden.value == value %} selected {% endif %}>
                        {{ key }}
                    </option>
                {% endfor %}
              </select>
            </div>
            <div class="form-group">
              <!-- Name attribute should match form attribute -->
              <label for="id_gender"> Gender </label>
              <select required id="id_gender" name="gender" placeholder="Gender" class="select-css">
                {% for value,key in hostel_form.fields.gender.choices %}
                    <option value="{{ value }}" {% if hostel_form.gender.value == value %} selected {% endif %}>
                        {{ key }}
                    </option>
                {% endfor %}
              </select>
            </div>

            <div class="form-group">
              <label for="id_mess"> Mess </label>
              <select required id="id_mess" name="mess" placeholder="Mess" class="select-css">
                {% for value,key in hostel_form.fields.mess.choices %}
                    <option value="{{ value }}"{% if hostel_form.mess.value == value %} selected {% endif %}>
                        {{ key }}
                    </option>
                {% endfor %}
              </select>
            </div>

            <!-- End HostelForm -->

            <input type="submit" class="reg_button" value="Add Hostel">
          </form>
        </div>
      </div>
    </div>
  {% endif %}
</div>

{% endblock %}

templates/hostel_app/add_room.html
<!DOCTYPE html>
{% extends "hostel_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
<div>
  {% if not is_warden %}
    <h2 style="text-align:center;">Only wardens can add Rooms</h2>
  {% else %}
    <!-- <h1>Add room</h1> -->
    <div class="main-w3layouts wrapper">
      <div class="main-agileinfo">
        <div class="agileits-top">
          {% if room_added %}
            <script>
            alert("Room Added!!");
            </script>
          {% endif %}
          <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% if room_form.errors %}
              <div class="alert alert-danger" role="alert">
                <div class="error">
                   <ul>
                     {% for key,value in room_form.errors.items %}
                      {% for error in value %}
                        <li>{{ error }}</li>
                      {% endfor %}
                     {% endfor %}
                   </ul>
                </div>
              </div>
            {% endif %}
            <!-- RoomForm -->

            <div class="form-group">
              <label for="id_hostel"> Hostel </label>
              <select required id="id_hostel" name="hostel" placeholder="Room" class="select-css">
                {% for value,key in room_form.fields.hostel.choices %}
                    <option value="{{ value }}">
                        {{ key }}
                    </option>
                {% endfor %}
              </select>
            </div>

            <div class="form-group">
              <label for="id_room"> Room Number</label>
              <input required class="textarea-css" type="number" name="room_num" placeholder="Room Number">
            </div>
            <div class="form-group">
              <label for="cap"> Accessibility </label>
              <input required class="textarea-css" type="number" min="0" max="1" name="capacity" placeholder="0-No / 1-Yes">
            </div>
            <!-- End RoomForm -->

            <input type="submit" class="reg_button" value="Add room">
          </form>
        </div>
      </div>
    </div>
  {% endif %}
</div>

{% endblock %}

templates/hostel_app/login.html
<!DOCTYPE html>
{% extends 'hostel_app/base.html' %}
{% block body_block%}

  <!-- <h1>Please login</h1> -->
  <div class="main-w3layouts wrapper">
    <div class="main-agileinfo">
      <div class="agileits-top">
        <form action="{% url 'hostel_app:user_login'%}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <input class="textarea-css" type="text" name="username" placeholder="Username">
          </div>
          <div class="form-group">
            <input class="textarea-css" type="password" name="password" placeholder="Password">
          </div>
          <input type="submit" class="btn btn-success" value="Login">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/hostel_app/reg.html
<!DOCTYPE html>
{% extends "hostel_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
<div>
  <style>
    div.a-full {
      width: 100%;
      height: 100%;
      display: flex;
      align-items: center;
      margin-top: 100px;
      margin-bottom: 50px;
      justify-content: center;
    }
    div.a-central-div {
      padding: 0 40px;
      border-color: white;
      border-width: 10px;
      border-style: solid;
      border-collapse: separate;
    }
  </style>
  {% if registered %}
    <div class="container">
      <div class="jumbotron" style="margin-top: 200px;">
        <h2>Room has been alotted</h2>
        <h2>Login to view your profile</h2>
      </div>
    </div>
  {% else %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-6">
          <div class="main-w3layouts">
            <div class="main-agileinfo-reg">
              <div class="agileits-top-reg">
                <form enctype="multipart/form-data" method="post">
                  {% csrf_token %}
                  {% if user_form.errors %}
                    <div class="alert alert-danger" role="alert">
                      <div class="error">
                         <ul>
                           {% for key,value in user_form.errors.items %}
                            {% for error in value %}
                              <li>{{ error }}</li>
                            {% endfor %}
                           {% endfor %}
                         </ul>
                      </div>
                    </div>
                    {% endif %}
                    {% if student_form.errors %}
                    <div class="alert alert-danger" role="alert">
                      <div class="error">
                         <ul>
                           {% for key,value in student_form.errors.items %}
                            {% for error in value %}
                              <li>{{ error }}</li>
                            {% endfor %}
                           {% endfor %}
                         </ul>
                      </div>
                    </div>
                  {% endif %}
                 
                  <div class="form-group">
                    <label for="id_mis"> MIS </label>
                    <input required class="textarea-css" type="text" name="mis_id" placeholder="MIS" value="{% if clg_form.mis.value %}{{clg_form.mis.value}}{% else %}{% endif %}">
                    
                  
                  <!-- UserForm -->
                  <div class="form-group">
                    <label for="id_username"> Username (Your hostel ID) </label>
                    <input required id="id_username" class="textarea-css" placeholder="Username" type="text" name="username" value="{% if user_form.username.value %}{{user_form.username.value}}{% else %}{% endif %}" autocomplete="false">
                  
                  </div>

                  <div class="form-group">
                    <label for="id_password"> Password </label>
                    <input required id="id_password" class="textarea-css" placeholder="Password" type="password" name="password" value="{% if user_form.password.value %}{{user_form.password.value}}{% else %}{% endif %}" autocomplete="false">
                  </div>

                  <!-- End UserForm -->

                  <!-- StudentForm -->
              
                  <!-- <div class="form-group">
                    <label for="email"> Email</label>
                    <input required class="textarea-css" type="email" name="email" placeholder="Email" value="{% if clg_form.email.value %}{{clg_form.email.value}}{% else %}{% endif %}">
                  </div>
                  <div class="form-group">
                    <label for="phone"> Phone number</label>
                    <input required class="textarea-css" type="number" name="phone_no" placeholder="Phone No." value="{% if clg_form.phone_no.value %}{{clg_form.phone_no.value}}{% else %}{% endif %}">
                  </div> 
                  <div class="form-group">
                    <label for="batch"> Batch of </label>
                    <input required class="textarea-css" type="number" name="batchof" placeholder="Passout Year" value="{% if clg_form.batchof.value %}{{clg_form.batchof.value}}{% else %}{% endif %}">
                  </div> -->
                    <!-- Name attribute should match form attribute -->
                  
                  <div class="form-group">
                    <label for="id_student_name"> Name </label>
                    <input required class="textarea-css" type="text" name="student_name" placeholder="Name" value="{% if student_form.student_name.value %}{{student_form.student_name.value}}{% else %}{% endif %}">
                  </div>
                  <div class="form-group">
                    <label for="id_gender"> Gender </label>
                    <select required id="id_gender" name="gender" placeholder="Gender" class="select-css">
                      {% for value,key in student_form.fields.gender.choices %}
                          <option value="{{ value }}" {% if student_form.gender.value == value %} selected {% endif %}>
                              {{ key }}
                          </option>
                      {% endfor %}
                    </select>
                  </div>

                  <!-- <div class="form-group">
                    <label for="id_branch"> Department </label>
                    <select required id="id_branch" name="branch" placeholder="Branch" class="select-css" value="Computers"> <!-- "{{clg_form.branch.value}}"> -->
                      <!-- {% for value,key in clg_form.fields.branch.choices %} --> 
                           <!-- <h1>{{student_form.branch}}</h1>  -->
                           <!-- <option value="{{ value }}" {% if clg_form.branch.value == value %} selected {% endif %}>
                              {{ key }}
                          </option>
                      {% endfor %}
                    </select>
                  </div>  -->

                  <div class="form-group">
                    <label for="id_room"> Room </label>
                    <select required id="id_room" name="room" placeholder="Room" class="select-css">
                      {% for value,key in student_form.fields.room.choices %}
                          <option value="{{ value }}" {% if student_form.room.choices.value == value %} selected {% endif %}>
                              {{ key }}
                          </option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="veh"> Do you own a vehicle at hostel? </label>
                    <select required id="veh" name="own_vehicle" placeholder="Yes/No" class="select-css">
                      {% for value,key in student_form.fields.own_vehicle.choices %}
                          <option value="{{ value }}" {% if student_form.own_vehicle.choices.value == value %} selected {% endif %}>
                              {{ key }}
                          </option>
                      {% endfor %}
                    </select>
                  </div>
                  <!-- End StudentForm -->

                  <input type="submit" class="reg_button" value="Register">
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6" style="float: right; position: fixed; top: 40px; right: 0;">
          <div class="a-full">
            <div class="a-central-div" style="float: left;">
              {% if boys_hostel %}
              <h2>Boys Hostel</h2>
                  {% for hostel in boys_hostel %}
                      <p>{{hostel.hostel_name}}</p>
                  {% endfor %}
              {% endif %}

              {% if girls_hostel %}
              <h2>Girls Hostel</h2>
                  {% for hostel in girls_hostel %}
                      <p>{{hostel.hostel_name}}<p>
                  {% endfor %}
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
</div>
{% endblock %}